-- drive_queue — the Design Engine "Send to Drive -> Media Buyer" button inserts rows here;
-- design-engine/cli/drive_pull.py drains them into the Media Buyer Google Drive folder.
-- Run once in the Supabase SQL editor (project bfzvxxcsfxvgeblnkqne).

create table if not exists public.drive_queue (
  id            bigint generated by default as identity primary key,
  sku           text,
  creative_name text,
  image_url     text not null,
  folder        text default 'Media Buyer',
  status        text default 'pending',   -- pending | done | error
  drive_file_id text,
  note          text,
  created_at    timestamptz default now()
);

alter table public.drive_queue enable row level security;

-- Allow the anon/publishable key to INSERT from the static engine (same pattern as ad_approvals).
create policy "engine can queue" on public.drive_queue
  for insert to anon with check (true);

-- (Reads/updates are done by drive_pull.py with the service_role key, which bypasses RLS.)
